name: CMake Test

on: 
  repository_dispatch:
    types: 
      [test_pr]

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5

    - name: Install octokit/core.js
      run: npm install @octokit/core
    
    - name: Install xmlhttprequest
      run: npm install xmlhttprequest
    
      #Get Repository that isn't currently being checked
    - name: Get a Pull Request's Repo Name that isn't already being checked
      run: node .cbc/getRepoInfo.js ${{ secrets.AUTH_TOKEN }} full_name > repo.txt

    - name: Save Repository name as Output Variable
      id: repo
      uses: juliangruber/read-file-action@v1
      with:
        path: repo.txt
    
    - name: Get the Pull Request's Number
      run: node .cbc/getRepoInfo.js ${{ secrets.AUTH_TOKEN }} number > number.txt

    - name: Save Repository Number as Output Variable
      id: number
      uses: juliangruber/read-file-action@v1
      with:
        path: number.txt

    - name: Add "currentlyBeingChecked" label
      run: node .cbc/addLabel.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} currentlyBeingChecked

      #Add CMake tests below this line

      #Problem 1 Testing
    - name: Problem 1, Get root CMakeLists.txt
      id: p1getCMakeLists1
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem1/CMakeLists.txt > problem1/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, CMakeLists.txt found in root"

    - name: Problem 1, Get apps CMakeLists.txt
      id: p1getCMakeLists2
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem1/apps/CMakeLists.txt > problem1/apps/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, CMakeLists.txt found in apps"

    - name: Problem 1, Get include CMakeLists.txt
      id: p1getCMakeLists3
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem1/include/CMakeLists.txt > problem1/include/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, CMakeLists.txt found in include"

    - name: Problem 1, Create Build
      id: p1build
      run: |
        cd problem1
        mkdir build
        cd build

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Build directory created"

    - name: Problem 1, Run CMake
      id: p1runCMake
      run: |
        cd problem1/build
        cmake ..   

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Makefile created"

    - name: Problem 1, Run Make
      id: p1runMake
      run: |
        cd problem1/build
        make

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Makefile ran"

    - name: Problem 1, Run program
      id: p1runProgram
      run: ./problem1/build/apps/hello > output1.log

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Executable ran"

    - name: Problem 1, Read Output1
      id: p1output
      uses: juliangruber/read-file-action@v1
      with:
        path: output1.log

    - name: Problem 1, Assert Proper Output
      id: p1properOutput
      uses: therussiankid92/gat@v1.5
      with:
        assertion: should.equal
        actual: ${{ steps.output1.outputs.content }}
        expected: ${{ secrets.PROGRAM_OUTPUT1 }}
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Executable output is correct"

    - name: Problem 1, Make clean
      id: p1makeClean
      run: |
        cd problem1/build
        make clean

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Makefile clean function ran"

    - name: Problem 1, Find File
      continue-on-error: true
      run: |
        cd problem1/build
        echo "Found? " > clean.txt
        test -f tree && echo "Yes" >> clean.txt

    - name: Problem 1, Read Find Output
      id: p1find
      uses: juliangruber/read-file-action@v1
      with:
        path: problem1/build/clean.txt

    - name: Problem 1, Assert File Gone
      id: p1fileGone
      uses: therussiankid92/gat@v1.5
      with:
        assertion: should.equal
        actual: ${{ steps.find.outputs.content }}
        expected: Found?
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1, Makefile clean function deleted the tree executable"

      #Problem 2 Testing
    - name: Get root CMakeLists.txt
      id: getCMakeLists1
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem2/CMakeLists.txt > problem2/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "CMakeLists.txt found in root"

    - name: Get harp CMakeLists.txt
      id: getCMakeLists2
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem2/harp/CMakeLists.txt > problem2/harp/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "CMakeLists.txt found in harp"

    - name: Get lib CMakeLists.txt
      id: getCMakeLists3
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} problem2/lib/CMakeLists.txt > problem2/lib/CMakeLists.txt

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "CMakeLists.txt found in lib"

    - name: Create Build
      id: build
      run: |
        cd problem2
        mkdir build
        cd build

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Build directory created"

    - name: Run CMake
      id: runCMake
      run: |
        cd problem2/build
        cmake ..   

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Makefile created"

    - name: Run Make
      id: runMake
      run: |
        cd problem2/build
        make

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Makefile ran"

    - name: Run program
      id: runProgram
      run: ./problem2/build/perform > output.log

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Executable ran"

    - name: Read Output
      id: output
      uses: juliangruber/read-file-action@v1
      with:
        path: output.log

    - name: Assert Proper Output
      id: properOutput
      uses: therussiankid92/gat@v1.5
      with:
        assertion: should.equal
        actual: ${{ steps.output.outputs.content }}
        expected: ${{ secrets.PROGRAM_OUTPUT }}
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Executable output is correct"

    - name: Make clean
      id: makeClean
      run: |
        cd problem2/build
        make clean

    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Makefile clean function ran"

    - name: Find File
      continue-on-error: true
      run: |
        cd problem2/build
        echo "Found? " > clean.txt
        test -f tree && echo "Yes" >> clean.txt

    - name: Read Find Output
      id: find
      uses: juliangruber/read-file-action@v1
      with:
        path: problem2/build/clean.txt

    - name: Assert File Gone
      id: fileGone
      uses: therussiankid92/gat@v1.5
      with:
        assertion: should.equal
        actual: ${{ steps.find.outputs.content }}
        expected: Found?
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Makefile clean function deleted the tree executable"

   # - name: Assert No Variables, Automatic Variables, Pattern Matching, or Makefile Functions in MakeFile1.txt
   #   id: assertNoVariables
   #   run: node .cbc/assertDoesNotContain.js Makefile "$,@,<,%,="
    
   # - name: Comment
   #   run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Makefile1.txt doesn't contain Variables, Automatic Variables, Pattern Matching, or Makefile Functions"

      #Issue Badge -- Do not change!! 
    - name: Get email.txt
      id: getEmail
      run: node .cbc/getFile.js ${{ secrets.AUTH_TOKEN }} ${{ steps.repo.outputs.content }} email.txt > email.txt

    - name: Save Email as Output Variable
      id: userEmail
      uses: juliangruber/read-file-action@v1
      with:
        path: email.txt
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Email found - ${{ steps.userEmail.outputs.content }}"

    - name: Issue Badge
      id: issueBadge
      run: node .cbc/badgeAPI.js ${{secrets.USERNAME}} ${{secrets.PASSWORD}} ${{ steps.userEmail.outputs.content }}
    
    - name: Comment
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Badge Issued. Congratulations!"
    
      #Failure Output for Problem 1 -- change
    - name: Failure Comment
      if: always() && steps.p1getCMakeLists1.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - No CMakeLists.txt found in root"
    
    - name: Failure Comment
      if: always() && steps.p1getCMakeLists2.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - No CMakeLists.txt found in apps"

    - name: Failure Comment
      if: always() && steps.p1getCMakeLists3.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - No CMakeLists.txt found in include"

    - name: Failure Comment
      if: always() && steps.p1build.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Build directory not created"

    - name: Failure Comment
      if: always() && steps.p1runCMake.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - CMakeLists.txt failed"

    - name: Failure Comment
      if: always() && steps.p1runMake.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Makefile didn't run"
    
    - name: Failure Comment
      if: always() && steps.p1runProgram.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Executable crashed"
    
    - name: Failure Comment
      if: always() && steps.p1properOutput.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Executable output was incorrect"
    
    - name: Failure Comment
      if: always() && steps.p1makeClean.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Makefile clean didn't run"

    - name: Failure Comment
      if: always() && steps.p1find.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Couldn't find clean.txt"
    
    - name: Failure Comment
      if: always() && steps.p1fileGone.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Problem 1 - Error - Makefile clean didn't delete the tree executable"

      #Failure Output for Problem 2 -- change
    - name: Failure Comment
      if: always() && steps.getCMakeLists1.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - No CMakeLists.txt found in root"
    
    - name: Failure Comment
      if: always() && steps.getCMakeLists2.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - No CMakeLists.txt found in harp"

    - name: Failure Comment
      if: always() && steps.getCMakeLists3.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - No CMakeLists.txt found in lib"

    - name: Failure Comment
      if: always() && steps.build.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Build directory not created"

    - name: Failure Comment
      if: always() && steps.runCMake.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - CMakeLists.txt failed"

    - name: Failure Comment
      if: always() && steps.runMake.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Makefile didn't run"
    
    - name: Failure Comment
      if: always() && steps.runProgram.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Executable crashed"
    
    - name: Failure Comment
      if: always() && steps.properOutput.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Executable output was incorrect"
    
    - name: Failure Comment
      if: always() && steps.makeClean.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Makefile clean didn't run"

    - name: Failure Comment
      if: always() && steps.find.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Couldn't find clean.txt"
    
    - name: Failure Comment
      if: always() && steps.fileGone.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Makefile clean didn't delete the tree executable"

    # - name: Failure Comment
    #   if: always() && steps.assertNoVariables.outcome == 'failure'
    #   run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Makefile has Variables, Automatic Variables, Pattern Matching, or Makefile Functions"

      #Failure Output for Issue Badge -- Probably don't change
    - name: Failure Comment
      if: always() && steps.getEmail.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - No email.txt found"

    - name: Failure Comment
      if: always() && steps.issueBadge.outcome == 'failure'
      run: node .cbc/makeComment.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} "Error - Badge issue failed - Email Address wasn't valid"

      #Close Pull Request -- Do not change!
    - name: Close Pull Request
      if: always()
      uses: peter-evans/close-pull@v1
      with:
        pull-request-number:  ${{ steps.number.outputs.content }}
        comment: Auto-closing pull request after submission
        delete-branch: false

    - name: Remove Previous Labels
      if: always()
      run: node .cbc/removeAllLabels.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }}
      
    - name: Add "checkComplete" label
      if: always()
      run: node .cbc/addLabel.js ${{ secrets.AUTH_TOKEN }} ${{ steps.number.outputs.content }} checkComplete
